### ISSUE TITLE
Some improvement on bazin curve fitting

### ISSUE THREAD

**Issue by aerdem4** [COINtoolbox/ActSNClass#1]
Thanks a lot for your repo. I have used your bazin curve fitting on the PLAsTiCC Competition (https://www.kaggle.com/c/PLAsTiCC-2018) and it improved my score significantly. I have updated the code such that it incorporates with flux error and passband too. I don't know if it makes sense from your perspective but it is an improvement that you may also use it: https://github.com/aerdem4/kaggle-plasticc/blob/master/bazin.py

**Comment by emilleishida** [comment]
hi @aerdem4 thanks a lot for your comment!
We are very happy to know that the example we provided was useful in the challenge!

May I ask you to check the url in your message? I got an error when I try to access it. 
Maybe the address has changed.

**Comment by aerdem4** [comment]
Hi @emilleishida , sorry I am still working on cleaning my repo, therefore it changed path. Here is its new path: https://github.com/aerdem4/kaggle-plasticc/blob/master/feature_extraction/bazin.py Let me know if you have any questions.
