### ISSUE TITLE
repeated code in classifiers

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/ActSNClass#14]
The classifiers module has a lot of redundancy. 
We should make one unique function which handles all sklearn classifers.

**Comment by Yash-10** [comment]
I don't know if the issue is still active but I would love to take up this issue of no one has taken it yet.

**Comment by emilleishida** [comment]
hi @Yash-10, thanks for offering and sorry for the bad issue management. 
I forgot to update the status of this issue. It is closed now since we decided to remove extra classifiers from the pipeline.
